before_install:
  - yes | sudo add-apt-repository ppa:hansjorg/rust
  - sudo apt-get update
install:
  - sudo apt-get install rust-nightly
  - git clone https://github.com/bjz/sax-rs.git
  - ln -s ../sax-rs/src/sax/ src/sax
script:
  - rustpkg build gen
  - rustpkg build gl
